### ISSUE TITLE
Is there any plans to deploy lib to public  maven repo ? 

### ISSUE THREAD

**Issue by ryadar** [veehaitch/devicecheck-appattest#11]
Library is not available in public maven repo as of now.

Is there any plans to push lib to maven repo ?

**Comment by veehaitch** [comment]
It was always planned but the rather cumbersome process (GPG ❤️) always kept me from working on it. Thanks to your request, I finally did it: https://repo1.maven.org/maven2/ch/veehait/devicecheck/devicecheck-appattest/

As of yet, It is not visible to https://search.maven.org but it shouldn't be long.

**Comment by ryadar** [comment]
Thanks a lot for pushing library to public maven. 
I appreciate your help.
