### ISSUE TITLE
Exceptions are internal

### ISSUE THREAD

**Issue by p-barabas** [veehaitch/devicecheck-appattest#15]
Hi, 

I want to use the library in a java backend code. 
How can I differentiate the possible exceptions in attestation and assertion phase, since the exception classes are internal?
Is it possible to make exception classes visible outside?

**Comment by veehaitch** [comment]
Hey! Thanks for reporting this. Of course, you're right, the exception classes should be public. I changed the visibility in #16. Feel free to take a look.

**Comment by p-barabas** [comment]
Thanks
