### ISSUE TITLE
Is there any documentation to integrate this on my server?

### ISSUE THREAD

**Issue by victorlaerte** [veehaitch/devicecheck-appattest#4]
Is there any documentation to integrate this on my server? Or some example of it?

**Comment by veehaitch** [comment]
Thanks for the question! The README provides some hints on how to implement the attestation and assertion within your server application.

Typically, you would trigger an attestation when your users sign up for your iOS app or use a new device with their already existing account. Your iOS app should create an assertion whenever you deem it meaningful. One approach would be, for example, to just create an assertion for every HTTP request (body, some headers) and attach it to the request as an HTTP header. 

A self-contained example project which makes use of this library would be useful but does not yet exist. If you or anybody else creates one, I'm happy to link to it! 🙂
